fragment HomeParts on Home {
  __typename
  light {
    __typename
    heroTitle1
    heroTitle2
    heroSubtitle
    heroBackground
    introText1
    introText2
    introText3
  }
  dark {
    __typename
    heroTitle1
    heroTitle2
    heroSubtitle
    heroBackground
    introText1
    introText2
    introText3
  }
}

fragment AboutParts on About {
  __typename
  light {
    __typename
    heroImage
    name
    title
    email
    intro
    exhibitions {
      __typename
      year
      title
      location
    }
    artistStatement
  }
  dark {
    __typename
    heroImage
    name
    title
    email
    intro
    exhibitions {
      __typename
      year
      title
      location
    }
    artistStatement
  }
}

fragment NewsParts on News {
  __typename
  title
  date
  light {
    __typename
    title
    description
    coverImage
    body
    gallery
  }
  dark {
    __typename
    title
    description
    coverImage
    body
    gallery
  }
}

fragment Art_worksParts on Art_works {
  __typename
  title
  category
  year
  light {
    __typename
    title
    description
    coverImage
    body
    gallery
  }
  dark {
    __typename
    title
    description
    coverImage
    body
    gallery
  }
}

fragment GlobalParts on Global {
  __typename
  site {
    __typename
    title
    description
    email
  }
  navigation {
    __typename
    label
    href
  }
  social {
    __typename
    platform
    url
  }
  headerToggle {
    __typename
    leftText
    leftSubtitle
    rightText
    rightSubtitle
    leftColor
    rightColor
    leftTextColor
    rightTextColor
  }
}
